//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHC1.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPrgmRegistration
    {
        public int RegistrationID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string AgeGroup { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Message { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual tblPrgmRegistration tblPrgmRegistration1 { get; set; }
        public virtual tblPrgmRegistration tblPrgmRegistration2 { get; set; }
    }
}
